#!/bin/bash

FILES="/home/brady/dotfiles/files"
OLD="/home/brady/dotfiles/.old-files/"
PROMT="Would you like to overwrite"

# if [ -a ~/.vimrc ]; then 
#    echo "$PROMPT .vimrc?"
#    read ANS
#    if [[ $ANS == y ]]; then 
#       mv ~/.vimrc $OLD
#    fi
# fi

mkdir -p $OLD

if [[ -a ~/.vimrc ]] ; then mv ~/.vimrc $OLD ; fi
ln -sf $FILES/.vimrc ../.vimrc

if [[ -a ~/.zshrc ]] ; then mv ~/.zshrc $OLD ; fi
ln -sf $FILES/.zshrc ../.zshrc

if [[ -a ~/.bashrc ]] ; then mv ~/.bashrc $OLD ; fi
ln -sf $FILES/.bashrc ../.bashrc

if [[ -a ~/.aliases ]] ; then mv ~/.aliases $OLD ; fi
ln -sf $FILES/.aliases ../.aliases

if [[ -a ~/.tmux.conf ]] ; then mv ~/.tmux.conf $OLD ; fi
ln -sf $FILES/.tmux.conf ../.tmux.conf

if [[ -d ~/.vim/colors ]] ; then mv ~/.vim/colors/ $OLD ; fi
ln -sf $FILES/vim-colors/ ../.vim/colors/

if [[ -d ~/.vim/autoload ]] ; then mv ~/.vim/autoload/ $OLD ; fi
ln -sf "$FILES/vim-autoload" "../.vim/autoload/"

mkdir -p "~/bin/"
if [[ -a ~/bin/editvimrc ]] ; then mv ~/bin/editvimrc $OLD ; fi
ln -sf $FILES/bin-editvimrc ../bin/editvimrc

source ~/.bashrc

